management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
#      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"
      # exclude: env, beans # 제외할 actuator endpoint 제외 가능

# info의 env는 Environment에서 "info."으로 시작하는 정보 표시에 대한 것
info:
  app:
    name: "hello-actuator"
    company: "anonymous"
  writer: "backend-developer"

# 로깅 레벨 설정
logging:
  level:
    "hello.controller": "TRACE" # "" 없이 trace만 입력해도 가능 # 대문자가 아닌 소문자로 입력해도 가능(IntelliJ 자동 완성은 소문자에 대해 자동 완성 지원함)
    # root: "error" # 외부 설정값 logging.level.root로 로거가 있는 모든 패키지, 클래스에 대한 기본 로그 레벨 설정 가능
